"""add appointment_id to consultations

Revision ID: 97293600c284
Revises: 9c6bbb7a8b5e
Create Date: 2025-11-29 17:44:40.310564

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '97293600c284'
down_revision = '9c6bbb7a8b5e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('consultations', schema=None) as batch_op:
        batch_op.add_column(sa.Column('appointment_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'appointments', ['appointment_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('consultations', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('appointment_id')

    # ### end Alembic commands ###
