"""add pet_vaccines and fix pets structure

Revision ID: 9e7f1c6b5621
Revises: 3e098c521b2c
Create Date: 2025-11-21 22:50:36.590174

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9e7f1c6b5621'
down_revision = '3e098c521b2c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pet_vaccines',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('pet_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('lot', sa.String(length=80), nullable=True),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('next_dose', sa.Date(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['pet_id'], ['pets.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('pet_vaccines')
    # ### end Alembic commands ###
